export const UPDATECARD = {
    updates: [
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"green",
            type:"New",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"Blue",
            type:"Fix",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"purple",
            type:"Improvment",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"green",
            type:"New",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"blue",
            type:"Fix",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"purple",
            type:"Improvment",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"green",
            type:"New",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"blue",
            type:"Fix",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        },
        {
            vDate:"3.3.0 (14/05/2018)",
            bColor:"purple",
            type:"Improvment",
            image:"/assets/images/developer.jpg",
            devName:"Kevin Joe",
            text:"File system changed from dokan to CBFS Host Cloud Drive is now a network drive Various bug fixes and stability improvments Share permission re-design and optimization",
        }
    ]
}